# Generated by Django 2.2 on 2019-04-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name_of_package',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
