# Generated by Django 2.2 on 2019-04-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registr', '0004_auto_20190406_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='packages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registr.Package'),
        ),
    ]
