# Generated by Django 2.2 on 2019-04-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registr', '0005_auto_20190406_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
