# Generated by Django 2.2 on 2019-04-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registr', '0009_auto_20190420_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='asks_answers',
        ),
        migrations.RemoveField(
            model_name='package',
            name='tests',
        ),
        migrations.AddField(
            model_name='modeofstudy',
            name='asks_answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registr.AskAnswerMode'),
        ),
        migrations.AddField(
            model_name='modeofstudy',
            name='tests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registr.TestMode'),
        ),
    ]
