# Generated by Django 2.2 on 2019-04-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registr', '0010_auto_20190420_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='mode_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registr.ModeOfStudy'),
        ),
    ]
