# Generated by Django 2.1.7 on 2019-03-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20190325_2128'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerUser',
            new_name='CustomUser',
        ),
    ]
